### ISSUE TITLE
Error 400 on SERVER:

### ISSUE THREAD

**Issue by haduk** [jamtur01/puppet-hipchat#35]
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Info: Caching catalog for sy1adm-puppet.hosts.ippayments.com
Info: Applying configuration version '1432259707'
Notice: Finished catalog run in 6.82 seconds
Error: Could not send report: Error 400 on SERVER: Could not autoload puppet/reports/hipchat: Class Hipchat is already defined in Puppet::Reports
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/indirector/rest.rb:207:in `is_http_200?'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/indirector/rest.rb:174:in `save'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/indirector/indirection.rb:283:in `save'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/configurer.rb:250:in `send_report'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/configurer.rb:242:in `run_internal'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/configurer.rb:134:in `block in run'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/context.rb:64:in `override'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet.rb:244:in `override'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/configurer.rb:133:in `run'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/agent.rb:47:in `block (4 levels) in run'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/agent/locker.rb:20:in `lock'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/agent.rb:47:in `block (3 levels) in run'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/agent.rb:117:in `with_client'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/agent.rb:44:in `block (2 levels) in run'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/agent.rb:82:in `run_in_fork'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/agent.rb:43:in `block in run'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/application.rb:179:in `call'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/application.rb:179:in `controlled_run'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/agent.rb:41:in `run'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/application/agent.rb:356:in `onetime'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/application/agent.rb:322:in `run_command'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/application.rb:381:in `block (2 levels) in run'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/application.rb:507:in `plugin_hook'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/application.rb:381:in `block in run'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/util.rb:488:in `exit_on_fail'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/application.rb:381:in `run'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/util/command_line.rb:146:in `run'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/util/command_line.rb:92:in `execute'
/opt/puppet/bin/puppet:8:in `<main>'

**Comment by jamtur01** [comment]
This is a known Puppet issue not a problem with the processor.
