### ISSUE TITLE
Feature Request: Username highlight

### ISSUE THREAD

**Issue by claflico** [jamtur01/puppet-hipchat#39]
In addition to the room notification function, could we add a user mention function as well so that we could pass an array of users to ping when they are in the room? I use Adium to connect to hipchat and don't get icon notifications when a run fails.

**Comment by james-powis** [comment]
@claflico Thanks for the request, however I have significant conflicts with adding arbitrary `@bob @steve` array expansions, for one every time a user is added the puppetserver has to be reloaded to pick up the change... I would suggest reaching out to the audium team to address the lack of feature in the client you are using.

**Comment by james-powis** [comment]
@claflico this module has been migrated to voxpupuli (https://github.com/voxpupuli/puppet-report_hipchat) if this is still an desired feature please create an issue there.
