### ISSUE TITLE
Custom messages 

### ISSUE THREAD

**Issue by dvenrao** [jamtur01/puppet-hipchat#45]
Can I Send custom notifications messages to hipchat only like begging & ending of deployment process using puppet.

**Comment by james-powis** [comment]
@dvenrao at this time this module exclusively is a puppet report notifier, However my employer had a need for such custom notification functionality, and I used this module and its config files as a template to writing custom functions in puppet to accomplish just that.

**Comment by james-powis** [comment]
Closing due to module migration: https://github.com/voxpupuli/puppet-report_hipchat
