### ISSUE TITLE
Module name space collision 

### ISSUE THREAD

**Issue by james-powis** [jamtur01/puppet-hipchat#49]
@jamtur01 https://forge.puppet.com/puppetlabs/puppet_hipchat collides with this module in the land of namespace... Unfortunately PE users who want to utilize the new PE hipchat "chatops" integrations have to decide between using that, and receiving report notifications... I am very conflicted on how to address moving forward, obviously Puppet is the big dog so i guess if we wish to address this we need to end of life this module and create a newly named module such as 'hipchat_report'. 

What are your thoughts?

**Comment by jamtur01** [comment]
@james-powis @ccaum emailed about this a while ago. I'd suggest renaming the module, seeing if Carl or @ryanycoleman can redirect the current forge modules to a new namespace.

**Comment by james-powis** [comment]
@jamtur01 I think renaming or redirecting directly has significant consequences... Namely if the old forge namespace were to be renamed, librarian and r10k module configs would point to a non-existent project. And for anyone pointing to the current git repository, they would be impacted by the module rename as well. 

I suspect the only option is to fork then rename, flag the old repository as End of Life and link to the new project in both git and in the forge. In this way current users are not impacted, and they can slowly as needed migrate to the new project.

**Comment by jamtur01** [comment]
@james-powis Sure. Seems reasonable. I miss the Forge was a bit more flexible on this. :(

**Comment by ccaum** [comment]
I apologize for creating this problem. In hindsight I should have just named it puppetlabs/puppet_hipchat_addon. @jamtur01, if you follow @james-powis's suggestion and fork/rename, I'd suggest renaming it to jamtur01/puppet_hipchat_reports.  I'll discuss with the module team about changing the name of the puppetlabs/puppet_hipchat module.

**Comment by james-powis** [comment]
@jamtur01 I talked with the folks over at Voxpupuli and they are open to the idea of rehoming this module under the vox name space while doing performing the rename. Procedure would be pretty simple:

1. Fork the git repository
2. rev up the git repository to v999.999.999 and update to provide a link to the Vox Fork
3. rev up the forge module to v999.999.999 and update to provide a link to the Vox Fork

As you own the module on the forge that is the only step you would need to actually perform, I can handle the rest.

**Comment by ccaum** [comment]
To follow up from my end, we will be renaming our module to puppetlabs/puppet_hipchat_addon soon. I'm currently working with our modules team on where it fits in the backlog.

**Comment by jamtur01** [comment]
Sure. Let's do it. @james-powis happy for you to run point.

**Comment by james-powis** [comment]
https://github.com/james-powis/puppet-report_hipchat/commit/199fc5fdb34227bd0cda4dec406ab2f73c9186d2 which is a large cleanup and refactor was just tested on servers which previously were running HEAD from this module all in all everything is running great which is surprising for a first test on a 221 additions and 126 deletions refactor... I will open the dialog with the Vox guys again and let them know we are ready for a rehome.

**Comment by james-powis** [comment]
https://github.com/voxpupuli/puppet-report_hipchat is now live

https://github.com/jamtur01/puppet-hipchat is now tagged v999.999.999 to denote no longer in migration, Readme has been updated to provide a link to the new module under vox.

@jamtur01 can you please tag https://forge.puppet.com/jamtur01/hipchat with v999.999.999 as well?

**Comment by jamtur01** [comment]
@james-powis I'm not seeing the updates and the tag? Did you push?

**Comment by jamtur01** [comment]
Done.

**Comment by james-powis** [comment]
heh pushed to my personal copy... sorry about that!

**Comment by james-powis** [comment]
@jamtur01 last thing to do is shutdown the ability to open an issue, that should make your life a  little bit quieter...
