### ISSUE TITLE
Push a latest version to the forge

### ISSUE THREAD

**Issue by cwood** [jamtur01/puppet-hipchat#50]
There are plenty of commits but the forge is on a super old version.

Could you please push a latest version up to forge?

**Comment by james-powis** [comment]
Greetings @cwood, I apologize for the slow response, regretfully i have been largely offline due to personal issues, but rest assured I am back now. Due to an issue with a name space collision as discussed in #49 we are going to have to rename this module to make way for puppets hipchat integrations utility which shares its current name. 

It is my intention to republish with all the recent changes/improvements onto the forge, stay tuned and I will provide all the relevant links once this is complete.

**Comment by induja0107** [comment]
+1 to pushing the latest changes to the forge. Is it out there yet? Please let us know. Thanks!

**Comment by james-powis** [comment]
I just got the latest refactor / cleanup done in https://github.com/james-powis/puppet-report_hipchat/commit/199fc5fdb34227bd0cda4dec406ab2f73c9186d2 the goal is once I have a chance to vet this in the lab, we will be rehoming that repo under @voxpupuli

I am going to make this my priority to day, but given the holidays are upon us the move might take some time as people are already going on vacation.

**Comment by jamtur01** [comment]
@james-powis Do you need me to transfer the repo or anything?

**Comment by james-powis** [comment]
NO the intention was to keep this repo in place as the pulse shows pretty heavy clone-age, so the Vox guys would prefer that once that forked repo i just linked is ready we will transfer that one, then rev this repo and the forge module to 99.99.99 versions, will keep you in the loop @jamtur01

**Comment by james-powis** [comment]
My biggest concern is to not orphan any non-forge installations

**Comment by cwood** [comment]
I didnt know the vox people were taking over for this. I am fine making this PR there if it hasnt been fixed in the other repo.

**Comment by james-powis** [comment]
@cwood it was discussed a few times in the IRC channel, Namely due to #49 being the motivation

**Comment by jamtur01** [comment]
@james-powis Cool - thanks again for taking this over!

**Comment by cwood** [comment]
Which IRC channel? I see a lot of modules are being moved to teh Vox group.

**Comment by james-powis** [comment]
#voxpupuli on freenode

**Comment by cwood** [comment]
Sounds good. Ill close this out then.

**Comment by james-powis** [comment]
as part of the rehoming of the module, an update to the forge will happen keep an eye on #49
